// src/components/TransactionTable.vue
<template>
  <div class="table-wrap">
    <v-progress-linear indeterminate height="2" color="pointblue" v-if="loading"></v-progress-linear>
    <v-simple-table>
      <template v-slot:default>
        <thead class="thead">
          <tr>
            <th>Tx Hash</th>
            <th>Block</th>
            <th>Age</th>
            <th v-if="detail">Confirm</th>
            <th v-if="!embedMode">From</th>
            <th v-if="involved">Involved</th>
            <th>Action</th>
            <th v-if="detail"></th>
            <th v-if="detail || embedMode">Avatar</th>
          </tr>
        </thead>
        <tbody v-if="loading">
          <tr>
            <td colspan="100" style="height: 400px;background-color: white">
              <v-progress-circular color="pointblue" width="2" indeterminate></v-progress-circular>
            </td>
          </tr>
        </tbody>
        <tbody v-else-if="transactions.length == 0">
        <tr>
          <td colspan="100" style="height: 400px;background-color: white">
            <span class="grey--text">No Transactions</span>
          </td>
        </tr>
        </tbody>
        <transition-group name="list-complete" tag="tbody" v-else>
          <tr v-for="tx in transactions" :key="tx.id" class="row-item">
            <td>
              <router-link :to="{name: 'transaction', params: {id: tx.id}}" :target="embedMode ? '_blank' : ''">
                {{shortAddress(tx.id)}}
              </router-link>
            </td>
            <td><v-btn class="rect pointlink-btn" outlined small depressed  :target="embedMode ? '_blank' : ''" :to="{name: 'block', params: {index: tx.blockIndex}}">{{tx.blockIndex}}</v-btn></td>
            <td class="text-no-wrap">{{moment(tx.blockTimestamp || tx.timestamp).fromNow()}}</td>
            <td v-if="detail">
              <v-chip label small outlined text-color="#555"><strong class="mr-1">{{latestBlockIndex - tx.blockIndex + 1}}</strong> Confirms</v-chip>
            </td>

            <td v-if="!embedMode">
              <router-link :to="{name: 'account', params: {address: tx.object.signer}}" :target="embedMode ? '_blank' : ''">
                {{tx.object.signer.substr(0, 8)}}
              </router-link>
            </td>
            <td v-if="involved">
              <v-chip label small color="success" :outlined="tx.involved['type'] == 'INVOLVED'" v-if="tx.involved">{{tx.involved['type']}}</v-chip>
            </td>
            <td>
              <v-btn label small :to="{name: 'transaction', params: {id: tx.id}}" style="text-transform: none;height:26px;font-weight:500;letter-spacing: 0;color:#EBB077 !important;background-color: #FFFAF8 !important;font-weight: 600;padding:0 12px !important;" color="point" rounded outlined v-for="action in tx.actions" v-if="action.inspection" class="darken-1 px-2 mx-1" :target="embedMode ? '_blank' : ''">
                <v-btn icon x-small color="point" :to="{query: {action: action.inspection['typeId']}, ...((detail || embedMode) ? {} : {name: 'transactions'})}" style="width:12px;" class="mr-1"><v-icon x-small>mdi-filter-variant</v-icon></v-btn>
                {{action.inspection['typeId']}}
                <span style="font-size: 10px;opacity:0.8;" v-if="action.inspection['productType']">({{action.inspection['productType']}})</span>
              </v-btn>
            </td>
            <td v-if="detail">
              <span v-if="tx?.actions?.[0]?.inspection?.['amount']">
                <amount-label :asset-data="tx.actions[0].inspection['amount'][0]" :amount="tx.actions[0].inspection['amount'][1]" />
              </span>
            </td>
            <td v-if="detail || embedMode">
              <router-link :to="{name: 'avatar', params: {address: action.inspection['avatarAddress']}}" v-for="action in tx.actions" v-if="action.inspection" class="mx-1" :target="embedMode ? '_blank' : ''">
                {{action.inspection['avatarAddress'] && action.inspection['avatarAddress'].substr(0, 8)}}
              </router-link>
            </td>
          </tr>
        </transition-group>
      </template>
    </v-simple-table>
  </div>
</template>

<script>
import {mapGetters} from "vuex";
import AmountLabel from "@/components/ui/AmountLabel.vue";

export default {
    name: 'TransactionTable',
    components: {AmountLabel},
    props: {
        loading: {
            type: Boolean,
            default: false
        },
        transactions: {
            type: Array,
            default: []
        },
        detail: {
            type: Boolean,
            default: false
        },
        involved: {
            type: Boolean,
            default: false
        },
        embedMode: {
            type:Boolean,
            default: false
        }
    },
    mixins: [],
    data() {
        return {
        }
    },
    computed: {
        ...mapGetters('Block', ['latestBlockIndex'])
    },
    beforeDestroy() {
    },
    async created() {
    },
    methods: {
    }
}
</script>

<style scoped lang="scss">
.table-wrap {
  background-color: white;
}
.row-item {
  transition: all 0.5s;
}
.list-complete-enter, .list-complete-leave-to {
  transform: translateY(-40px);
  background-color: #f5f5fa;
}
.list-complete-leave-active {
  transition: none;
  position: absolute;
  opacity: 0;
}
</style>

// v2/src/components/TransactionTable.tsx
import { shortAddress, formatTimeAgo } from '@/utils/commonUtils';
import TableHeader, { TableHeaderCell } from './common/TableHeader';
import TableRow, { TableCell } from './common/TableRow';
import Link from './common/Link';
import AmountLabel from './common/AmountLabel';

export interface Action {
  inspection?: {
    typeId: string;
    productType?: string;
    amount?: [any, number];
    avatarAddress?: string;
  };
}

export interface Transaction {
  id: string;
  blockIndex: number;
  blockTimestamp?: string;
  timestamp: string;
  signer: string;
  involved?: {
    type: string;
  };
  actions: Action[];
}

export interface TransactionTableProps {
  loading: boolean;
  transactions: Transaction[];
  detail?: boolean;
  involved?: boolean;
  embedMode?: boolean;
  latestBlockIndex?: number;
}

export default function TransactionTable({
  loading,
  transactions,
  detail = false,
  involved = false,
  embedMode = false,
  latestBlockIndex = 0,
}: TransactionTableProps) {
  return (
    <div className="table-wrap bg-white">
      {loading && (
        <div className="h-0.5 bg-blue-600 animate-pulse"></div>
      )}
      <div className="overflow-x-auto">
        <table className="w-full">
          <TableHeader>
            <TableHeaderCell>Tx Hash</TableHeaderCell>
            <TableHeaderCell>Block</TableHeaderCell>
            <TableHeaderCell>Age</TableHeaderCell>
            {detail && <TableHeaderCell>Confirm</TableHeaderCell>}
            {!embedMode && <TableHeaderCell>From</TableHeaderCell>}
            {involved && <TableHeaderCell>Involved</TableHeaderCell>}
            <TableHeaderCell>Action</TableHeaderCell>
            {detail && <TableHeaderCell>Amount</TableHeaderCell>}
            {(detail || embedMode) && <TableHeaderCell>Avatar</TableHeaderCell>}
          </TableHeader>
          <tbody>
            {transactions.map((tx) => (
              <TableRow key={tx.id} className="row-item transition-all duration-500">
                <TableCell
                  className="text-blue-600 hover:text-blue-800"
                  style={{ fontFamily: 'Helvetica' }}
                >
                  <Link href={`/transaction/${tx.id}`} className="hover:underline">
                    {shortAddress(tx.id)}
                  </Link>
                </TableCell>
                <TableCell>
                  <Link
                    href={`/block/${tx.blockIndex}`}
                    className="inline-block px-3 py-1.5 text-xs bg-blue-50 text-blue-600 border border-blue-200 rounded hover:bg-blue-100 transition-colors"
                  >
                    {tx.blockIndex}
                  </Link>
                </TableCell>
                <TableCell className="text-gray-600 whitespace-nowrap">
                  {formatTimeAgo(tx.blockTimestamp || tx.timestamp)}
                </TableCell>
                {detail && (
                  <TableCell>
                    <div className="inline-flex items-center px-2 py-1 text-xs border border-gray-300 rounded bg-white text-gray-700">
                      <strong className="mr-1">{latestBlockIndex - tx.blockIndex + 1}</strong>
                      Confirms
                    </div>
                  </TableCell>
                )}
                {!embedMode && (
                  <TableCell
                    className="text-blue-600 hover:text-blue-800"
                    style={{ fontFamily: 'Helvetica' }}
                  >
                    <Link href={`/account/${tx.signer}`} className="hover:underline">
                      {tx.signer.substring(0, 8)}
                    </Link>
                  </TableCell>
                )}
                {involved && (
                  <TableCell>
                    {tx.involved && (
                      <div className={`inline-flex items-center px-2 py-1 text-xs rounded ${
                        tx.involved.type === 'INVOLVED' 
                          ? 'bg-green-50 text-green-700 border border-green-200' 
                          : 'bg-yellow-50 text-yellow-700 border border-yellow-200'
                      }`}>
                        {tx.involved.type}
                      </div>
                    )}
                  </TableCell>
                )}
                <TableCell>
                  {tx.actions.map(
                    (action, actionIndex) =>
                      action.inspection && (
                        <div
                          key={`${tx.id}-action-${actionIndex}`}
                          className="inline-flex items-center px-3 py-1 mx-1 text-xs rounded-full"
                          style={{
                            textTransform: 'none',
                            height: '26px',
                            fontWeight: 600,
                            letterSpacing: 0,
                            color: '#EBB077',
                            backgroundColor: '#FFFAF8',
                            padding: '0 12px'
                          }}
                        >
                          <button
                            type="button"
                            className="w-3 h-3 mr-1 text-orange-400 hover:text-orange-600"
                            aria-label="Filter by action type"
                            title="Filter by action type"
                          >
                            <svg
                              className="w-full h-full"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                              aria-hidden="true"
                            >
                              <path
                                fillRule="evenodd"
                                d="M3 3a1 1 0 011-1h12a1 1 0 011 1v3a1 1 0 01-.293.707L12 11.414V15a1 1 0 01-.293.707l-2 2A1 1 0 018 17v-5.586L3.293 6.707A1 1 0 013 6V3z"
                                clipRule="evenodd"
                              />
                            </svg>
                          </button>
                          {action.inspection.typeId}
                          {action.inspection.productType && (
                            <span style={{ fontSize: '10px', opacity: 0.8 }}>
                              ({action.inspection.productType})
                            </span>
                          )}
                        </div>
                      )
                  )}
                </TableCell>
                {detail && (
                  <TableCell className="text-gray-600">
                    {tx.actions[0]?.inspection?.amount && (
                      <AmountLabel
                        assetData={tx.actions[0].inspection.amount[0]}
                        amount={tx.actions[0].inspection.amount[1]}
                      />
                    )}
                  </TableCell>
                )}
                {(detail || embedMode) && (
                  <TableCell className="text-blue-600 hover:text-blue-800">
                    {tx.actions.map(
                      (action, actionIndex) =>
                        action.inspection?.avatarAddress && (
                          <Link
                            key={`${tx.id}-avatar-${actionIndex}`}
                            href={`/avatar/${action.inspection.avatarAddress}`}
                            className="mx-1 hover:underline"
                          >
                            {action.inspection.avatarAddress.substring(0, 8)}
                          </Link>
                        )
                    )}
                  </TableCell>
                )}
              </TableRow>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
