// v2/src/components/common/AmountLabel.tsx
interface AmountLabelProps {
  assetData?: {
    ticker?: string;
    decimalPlaces?: number;
  };
  amount?: number;
  minus?: boolean;
}

export default function AmountLabel({ assetData, amount, minus = false }: AmountLabelProps) {
  const ticker = assetData?.ticker || '';
  const decimal = Number(assetData?.decimalPlaces ?? 0);
  
  let displayAmount = (amount || 0) * (minus ? -1 : 1);
  if (decimal > 0) {
    displayAmount /= Math.pow(10, decimal);
  }

  return (
    <span className="amount" style={{ color: '#444', fontWeight: 500 }}>
      {displayAmount.toFixed(2)} <span className="ticker" style={{ color: '#666' }}>{ticker}</span>
    </span>
  );
}

// src/components/ui/AmountLabel.vue
<template>
  <span class="amount">
    {{ncgFormat(decimalAmount)}} <span class="ticker">{{ticker}}</span>
  </span>
</template>
<script>
export default {
  name: 'AmountLabel',
  props: {
    assetData: {
      type: Object
    },
    amount: {
      type: Number
    },
    minus: {
      type: Boolean,
      default: false
    }
  },
  components: {},
  mixins: [],
  data() {
    return {
    }
  },
  computed: {
    ticker() {
      return this.assetData?.['ticker'] || ""
    },
    decimalAmount() {
      const decimal = Number(this.assetData?.['decimalPlaces'] ?? 0)
      let amount = this.amount * (this.minus ? -1 : 1)
      if (decimal > 0) {
        amount /= Math.pow(10, decimal)
        return amount.toFixed(2)
      }
      return amount
    }
  },
  methods: {
  }
}
</script>

<style lang="scss">
.amount {
  color: #444;
  font-weight: 500;

  .ticker {
    color: #666;
  }
}
</style>
