// v2/src/components/TxHistoryChart.tsx
import { useRef } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Line } from 'react-chartjs-2';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend);

interface Block {
  index: number;
  timestamp: string;
  txCount: number;
}

interface TxHistoryChartProps {
  blocks: Block[];
  loading: boolean;
}

export default function TxHistoryChart({ blocks, loading }: TxHistoryChartProps) {
  const chartRef = useRef<ChartJS<'line'>>(null);

  const processData = () => {
    if (!blocks || blocks.length === 0) return { labels: [], data: [] };

    const sortedBlocks = [...blocks]
      .map((b) => ({ timestamp: b.timestamp, txCount: b.txCount, index: b.index }))
      .reverse();

    if (sortedBlocks.length > 0) {
      const startIndex = sortedBlocks[0].index - (sortedBlocks[0].index % 10);
      const filteredBlocks = sortedBlocks.filter((b) => b.index >= startIndex);

      const chunkedBlocks = [];
      for (let i = 0; i < filteredBlocks.length; i += 10) {
        chunkedBlocks.push(filteredBlocks.slice(i, i + 10));
      }

      const labels = chunkedBlocks.map((chunk) => {
        const first = chunk[0];
        const last = chunk[chunk.length - 1];
        return `${first.index}~${last.index}`;
      });

      const data = chunkedBlocks.map((chunk) => {
        const avgTx = chunk.reduce((sum, block) => sum + block.txCount, 0) / chunk.length;
        return avgTx;
      });

      return { labels, data };
    }

    return { labels: [], data: [] };
  };

  const { labels, data } = processData();

  const chartData = {
    labels,
    datasets: [
      {
        data,
        borderColor: '#f6a14c',
        borderWidth: 2,
        tension: 0.4,
        fill: false,
        radius: 0,
      },
    ],
  };

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      title: { display: false },
    },
    interaction: {
      intersect: false,
    },
    scales: {
      x: {
        display: false,
        title: { display: false },
      },
      y: { display: true },
    },
  };

  if (loading) {
    return (
      <div className="h-32 bg-gray-100 rounded flex items-center justify-center">
        <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-gray-400" />
      </div>
    );
  }

  return (
    <div className="h-32">
      <Line ref={chartRef} data={chartData} options={options} />
    </div>
  );
}

// src/components/ui/TxHistoryChart.vue
<template>
  <canvas height="130" width="300" style="max-height: 130px" id="tx-chart"></canvas>
</template>

<script>
import Chart from "chart.js/auto"
import {mapGetters} from "vuex";
export default {
    name: 'TxHistoryChart',
    props: {
    },
    components: {},
    mixins: [],
    data() {
        return {
            chart: null
        }
    },
    computed: {
        ...mapGetters('Block', ['latestBlockIndex', 'latestBlocksFull'])
    },
    mounted() {
        this.chart = new Chart(document.querySelector('#tx-chart'), {
            type: 'line',
            data: {
                labels: [],
                datasets: [{
                    data: [],
                    borderColor: '#f6a14c',
                    borderWidth: 2,
                    cubicInterpolationMode: 'monotone',
                    tension: 0.4,
                    fill: false,
                    radius: 0
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {display: false},
                    title: {display: false},
                },
                interaction: {
                    intersect: false,
                },
                scales: {
                    x: {
                        display: false,
                        title: {display: false}
                    },
                    y: {display: true}
                }
            }
        })

        this.$watch('latestBlockIndex', () => {
            this.update()
        })
        this.update()
    },
    methods: {
        update() {
            if (!this.chart) return
            let blocks = this.latestBlocksFull.map(b => ({timestamp: b.object.timestamp, txc: b.object.txCount, index: b.object.index})).reverse()
            if (blocks && blocks.length > 0) {
                blocks = blocks.splice(10 - (blocks[0].index % 10))
                this.chart.data.labels = _.chunk(blocks, 10).map(bs => bs[0].index + '~' + _.last(bs).index)
                this.chart.data.datasets[0].data = _.chunk(blocks, 10).map(bs => bs.map(b => b.txc).reduce((a,b) => a+b)/ bs.length)
                this.chart.update()
            }
        }
    }
}
</script>

<style lang="scss">
</style>
